version: '3.1'

services:
  app:
    container_name: vitabletech-node-app
    image: node:latest
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "chmod +x ./setup.sh && ./setup.sh"
    ports:
      - "${APP_PORT}:${PORT}" # Use the port number defined in .env for the host
    env_file:
      - .env

  db:
    container_name: vitabletech-db
    image: mariadb:10.6
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

  phpmyadmin:
    container_name: vitabletech-phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      PMA_ARBITRARY: 1
      PMA_USER: root
      PMA_PASSWORD: ${DB_PASSWORD}